---
- hosts: all
  become: false
  gather_facts: false
  vars_files:
    - vars/main.yml
    - vars/main2.yml

  tasks:
    - include_role:
        name: create_tomcat_container
        name: create_nginx_container
